minimum_pre_commit_version: 2.9.3
default_language_version:
  # force all unspecified python hooks to run python3
  python: python3
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        name: Check large files (>500kB)
        args: ["--maxkb=500"]
      - id: trailing-whitespace
        name: Trim trailing whitespaces
      - id: end-of-file-fixer
        name: Add empty line to end of file
      - id: check-merge-conflict
        name: Check unresolved merge conflicts
      - id: check-json
        name: Check JSON
      - id: check-yaml
        name: Check YAML
      - id: check-toml
        name: Check TOML
      - id: check-xml
        name: Check XML
  - repo: https://github.com/pycqa/isort
    rev: 5.10.0
    hooks:
      - id: isort
        name: Reorder python imports
  - repo: local
    hooks:
      - id: yapf
        name: Run yapf formatter
        entry: yapf
        language: system
        types: [python]
  - repo: local
    hooks:
      - id: pylint
        name: Run pylint analysis
        entry: pylint
        language: system
        types: [python]
